### ISSUE TITLE
How to use C++ member function in thread pool

### ISSUE THREAD

**Issue by rajenk** [mtrebi/thread-pool#7]
First of all thanks for your detailed write up to explain the code!

I am trying to use the threadpool submit function to take a C++ class member function. I am not able to compile. I followed standard std::thread  submitting a class member function method. Like the code shown below.
```c
class A
{
   int i;
public:
      A() { i =10; };
    ~A()
    void func1() { i++;};
};

A objA;

ThreadPool tPool(10);

tPool.submit(&A::func1,&objA);
```

But I am getting the following error.
error: no matching function for call to ‘ThreadPool::submit(void (A::*)(), A*)’

Does the current submit() template function accept class member function? If not can you provide some tip as to how this function can be modified to accept class member function?

Appreciate your help.

Here is the std::thread method of passing a non static member function.
```c
class Task
{
public:
	void execute(std::string command);
};

Task * taskPtr = new Task();

// Create a thread using member function
std::thread th(&Task::execute, taskPtr, "Sample Task");
```

Thanks,
Raj

**Comment by mtrebi** [comment]
Hey! I am glad you liked the readme, it took me some time to write it :+1: 

Regarding your question, yes, there's a way to pass member functions. Unfortunately I am now having some trouble with the compilers and I cannot test it.

In the meantime, you can solve the issue using std::bind. The idea is basically to create a new function that is simply the function we want to call with the specific object from which we want to call it. 

```c
auto func = std::bind(&A::func_1, &objA);
pool.submit(func);
```

You could do exactly the same using lambda expressions, is up to you to choose what you think is better.

Hope this helps!

**Comment by rajenk** [comment]
Thanks. I will  give std::bind a try or use lambda expressions. I will post the results to help answer others visiting your project.

Appreciate your quick reply.

**Comment by mtrebi** [comment]
Whenever I have some more time I will try to add an easier way to do it. I am really busy lately...

**Comment by rajenk** [comment]
I tried both bind and lambda approach. Both did not work the way I wanted in my app! So using a C wrapper functions to invoke member functions via the class object. This works for me as I intended.

**Comment by mtrebi** [comment]
I tried both options and they worked for me. What do you mean with ¨Both did not work the way I wanted?

Anyway, I am glad you found the solution to your problem :+1:
